### ISSUE TITLE
Error when setting initial date to December

### ISSUE THREAD

**Issue by vietdq2701** [Fingertips18/wheel-date-picker#9]
When I set the initialDate to December, it has an error, but if the months are from 1-11, there is no problem:

```
ScrollWheelDatePicker(
                    startDate: DateTime(2000),
                    initialDate: DateTime.parse('2024-12-24'),
                    theme: FlatDatePickerTheme(
                      backgroundColor: Colors.white,
                      overlay: ScrollWheelDatePickerOverlay.holo,
                      itemTextStyle:
                          Theme.of(context).textTheme.titleSmall?.copyWith(
                                fontSize: FontSize.fontSizeMedium,
                              ),
                      overlayColor: Colors.grey,
                      overAndUnderCenterOpacity: 0.3,
                    ),
                    onSelectedItemChanged: (DateTime date) {
                      selectedDate = date;
                    },
                  ),
                  
```

error log:
`======== Exception caught by widgets library =======================================================
The following RangeError was thrown building Container(bg: BoxDecoration(color: Color(0xffffffff), borderRadius: BorderRadius.circular(12.0))):
RangeError (length): Invalid value: Not in inclusive range 0..11: 12

When the exception was thrown, this was the stack: 
#0      List.[] (dart:core-patch/growable_array.dart)
#1      _getNumberOfDays (package:scroll_wheel_date_picker/src/date_controller.dart:474:22)
#2      new DateController (package:scroll_wheel_date_picker/src/date_controller.dart:59:21)
#3      _ScrollWheelDatePickerState.initState (package:scroll_wheel_date_picker/src/widgets/scroll_wheel_date_picker.dart:81:23)
#4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5748:55)
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593:5)
#6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468:16)
#7      MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:7035:36)
#8      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:7047:32)
...     Normal element mounting (13 frames)
#21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468:16)
#22     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:7035:36)
#23     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:7047:32)
...     Normal element mounting (303 frames)
#326    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468:16)
#327    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:7035:36)
#328    Element.updateChild (package:flutter/src/widgets/framework.dart:3963:18)
#329    Element.updateChildren (package:flutter/src/widgets/framework.dart:4150:32)
#330    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7060:17)
#331    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#332    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#333    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
`

**Comment by karloows** [comment]
Confirmed root cause: `initialDate.month` (1-indexed) was being passed straight into `_getNumberOfDays`, which indexes a 0-indexed 12-item list — December (`12`) read past the end. Fixed in #24, targeting `development`, with a regression test added. Will close automatically once that merges.
